let data = [{
        name: "Roxy Roisen",
        age: 59,
        gender: "Female",
        phone_number: "+92(507) 411 - 7230",
        email: "rroisen8 @msu.edu",
        address: "8540 Shelley Road",
    },
    {
        name: "Leesa Humm",
        age: 64,
        gender: "Female",
        phone_number: "+63(888) 225 - 4876",
        email: "lhumm7 @narod.ru",
        address: "21st Center",
    },
    {
        name: "Huntley Yushkov",
        age: 26,
        gender: "Male",
        phone_number: "+7(741) 480 - 6427",
        email: "hyushkov0@xrea.com",
        address: "1 Oakridge Alley",
    },
    {
        name: "Tomkin Borham",
        age: 28,
        gender: "Male",
        phone_number: "+86(826) 832 - 0039",
        email: "tborham6@addthis.com",
        address: "07 Ilene Court",
    },
    {
        name: "Kaine Burns",
        age: 35,
        gender: "Male",
        phone_number: "+95(344) 411 - 3174",
        email: "kburns5 @w3.org",
        address: "2921 Eastlawn Drive",
    },
    {
        name: "Mayer Langtree",
        age: 69,
        gender: "Male",
        phone_number: "+86(889) 443 - 1452",
        email: "mlangtree4 @toplist.cz",
        address: "83922 Ohio Junction Yushkov",
    },
    {
        name: "Colin Bispham",
        age: 55,
        gender: "Male",
        phone_number: "+86(853) 935 - 9207",
        email: "cbispham3 @comcast.net",
        address: "971 Dunning Point",
    },
    {
        name: "Carlos Sturdey",
        age: 35,
        gender: "Male",
        phone_number: "+380(932) 968 - 0627",
        email: "csturdey2 @wix.com",
        address: "722 Forest Dale Point",
    },
    {
        name: "Gasparo Songist",
        age: 55,
        gender: "Male",
        phone_number: "+63(849) 847 - 5620",
        email: "gsongist1 @jalbum.net",
        address: "10 Holy Cross Drive",
    },
    {
        name: "Lexi Wevell",
        age: 64,
        gender: "Female",
        phone_number: "+86(952) 163 - 1345",
        email: "lwevell9 @ovh.net",
        address: "93530 Huxley Plaza",
    },
    {
        name: "Adan Bracken",
        age: 50,
        gender: "Female",
        phone_number: "2492710523",
        email: "abracken0@webmd.com",
        address: "9 Darwin Street",
    },
    {
        name: "Etan Serraillier",
        age: 61,
        gender: "Male",
        phone_number: "4254152823",
        email: "eserraillier1@arstechnica.com",
        address: "1680 Buell Hill",
    },
    {
        name: "Felicity Binding",
        age: 64,
        gender: "Female",
        phone_number: "4011912221",
        email: "fbinding2@livejournal.com",
        address: "63951 Linden Junction",
    },
    {
        name: "Sadella Jackett",
        age: 83,
        gender: "Female",
        phone_number: "2167924064",
        email: "sjackett3@hp.com",
        address: "0 Westend Way",
    },
    {
        name: "Lonny Panner",
        age: 65,
        gender: "Male",
        phone_number: "7349006747",
        email: "lpanner4@themeforest.net",
        address: "33 Dixon Avenue",
    },
    {
        name: "Nadine Rivett",
        age: 50,
        gender: "Female",
        phone_number: "2234288688",
        email: "nrivett5@flavors.me",
        address: "6 Meadow Valley Trail",
    },
    {
        name: "Dilly Langdon",
        age: 37,
        gender: "Male",
        phone_number: "5993732572",
        email: "dlangdon6@odnoklassniki.ru",
        address: "46 Daystar Center",
    },
    {
        name: "Mayer Greguol",
        age: 76,
        gender: "Male",
        phone_number: "9167226269",
        email: "mgreguol7@time.com",
        address: "64 Fieldstone Street",
    },
    {
        name: "Raynard Tangye",
        age: 63,
        gender: "Male",
        phone_number: "9462755829",
        email: "rtangye8@techcrunch.com",
        address: "49365 Hansons Lane",
    },
    {
        name: "Lebbie Kernell",
        age: 33,
        gender: "Female",
        phone_number: "1807755135",
        email: "lkernell9@yandex.ru",
        address: "6968 New Castle Center",
    },
    {
        name: "Reeta Hackforth",
        age: 34,
        gender: "Female",
        phone_number: "1445212837",
        email: "rhackfortha@topsy.com",
        address: "128 Rusk Park",
    },
    {
        name: "Quintin Combe",
        age: 72,
        gender: "Male",
        phone_number: "2369536738",
        email: "qcombeb@wisc.edu",
        address: "982 Barby Junction",
    },
    {
        name: "Jdavie Antrobus",
        age: 39,
        gender: "Male",
        phone_number: "7207752671",
        email: "jantrobusc@cpanel.net",
        address: "2 Marquette Road",
    },
    {
        name: "Chanda Kinder",
        age: 65,
        gender: "Female",
        phone_number: "8161246224",
        email: "ckinderd@japanpost.jp",
        address: "45467 Northwestern Plaza",
    },
    {
        name: "Doralyn Spradbrow",
        age: 73,
        gender: "Female",
        phone_number: "5208757858",
        email: "dspradbrowe@cornell.edu",
        address: "13239 Hazelcrest Point",
    },
    {
        name: "Glenda Gleder",
        age: 34,
        gender: "Female",
        phone_number: "6975351237",
        email: "gglederf@tiny.cc",
        address: "835 Ronald Regan Center",
    },
    {
        name: "Frederique Aldham",
        age: 78,
        gender: "Female",
        phone_number: "6199951061",
        email: "faldhamg@woothemes.com",
        address: "2418 Warrior Center",
    },
    {
        name: "Morty Tufts",
        age: 66,
        gender: "Male",
        phone_number: "3966112113",
        email: "mtuftsh@multiply.com",
        address: "16 Loomis Court",
    },
    {
        name: "Wallie Andrivel",
        age: 36,
        gender: "Female",
        phone_number: "5251165682",
        email: "wandriveli@squidoo.com",
        address: "97961 Starling Crossing",
    },
    {
        name: "Tabby McCosker",
        age: 44,
        gender: "Female",
        phone_number: "7947246763",
        email: "tmccoskerj@washington.edu",
        address: "07 Mayfield Point",
    },
    {
        name: "Vasilis Gwinnell",
        age: 43,
        gender: "Male",
        phone_number: "8796741983",
        email: "vgwinnellk@pagesperso-orange.fr",
        address: "0353 Summerview Lane",
    },
    {
        name: "Ford Ilieve",
        age: 37,
        gender: "Male",
        phone_number: "3891534145",
        email: "filievel@wikimedia.org",
        address: "0 Reindahl Plaza",
    },
    {
        name: "Hussein Blazej",
        age: 81,
        gender: "Male",
        phone_number: "2744746573",
        email: "hblazejm@bloomberg.com",
        address: "4 Sugar Avenue",
    },
    {
        name: "Borden Giannini",
        age: 43,
        gender: "Male",
        phone_number: "5183878576",
        email: "bgianninin@wikimedia.org",
        address: "67276 Russell Road",
    },
    {
        name: "Devlin Olekhov",
        age: 54,
        gender: "Male",
        phone_number: "1806077398",
        email: "dolekhovo@hexun.com",
        address: "86 Merry Drive",
    },
    {
        name: "Kimberly Dundin",
        age: 35,
        gender: "Female",
        phone_number: "3635996024",
        email: "kdundinp@technorati.com",
        address: "91 Village Green Circle",
    },
    {
        name: "Raff Willsmore",
        age: 41,
        gender: "Male",
        phone_number: "9561768703",
        email: "rwillsmoreq@cyberchimps.com",
        address: "093 Norway Maple Trail",
    },
    {
        name: "Bertram Hempshall",
        age: 59,
        gender: "Male",
        phone_number: "9512004951",
        email: "bhempshallr@amazonaws.com",
        address: "6117 Lien Circle",
    },
    {
        name: "Odo Arsmith",
        age: 32,
        gender: "Male",
        phone_number: "9761278369",
        email: "oarsmiths@jalbum.net",
        address: "9830 Crowley Drive",
    },
    {
        name: "Launce Stucksbury",
        age: 60,
        gender: "Male",
        phone_number: "6934159980",
        email: "lstucksburyt@imageshack.us",
        address: "35 Center Hill",
    },
    {
        name: "Shem Lysons",
        age: 40,
        gender: "Male",
        phone_number: "2281862721",
        email: "slysonsu@chicagotribune.com",
        address: "1 3rd Alley",
    },
    {
        name: "Cristin Coldman",
        age: 51,
        gender: "Female",
        phone_number: "4795355964",
        email: "ccoldmanv@spotify.com",
        address: "39864 Clarendon Plaza",
    },
    {
        name: "Aile Bateman",
        age: 41,
        gender: "Female",
        phone_number: "3058089180",
        email: "abatemanw@list-manage.com",
        address: "4011 Oxford Street",
    },
    {
        name: "Danit Tosspell",
        age: 43,
        gender: "Female",
        phone_number: "4133218044",
        email: "dtosspellx@youku.com",
        address: "36 Vahlen Point",
    },
    {
        name: "Allianora Brimman",
        age: 77,
        gender: "Female",
        phone_number: "4979501155",
        email: "abrimmany@123-reg.co.uk",
        address: "015 Dawn Parkway",
    },
    {
        name: "Aguie McAdam",
        age: 50,
        gender: "Male",
        phone_number: "5106253014",
        email: "amcadamz@miitbeian.gov.cn",
        address: "2285 Kennedy Way",
    },
    {
        name: "Rosamond O'Dyvoie",
        age: 82,
        gender: "Female",
        phone_number: "6257203952",
        email: "rodyvoie10@amazon.com",
        address: "4709 Oxford Crossing",
    },
    {
        name: "Luci Ellwood",
        age: 83,
        gender: "Female",
        phone_number: "4931467974",
        email: "lellwood11@clickbank.net",
        address: "74273 Morrow Point",
    },
    {
        name: "Goraud Yateman",
        age: 63,
        gender: "Male",
        phone_number: "7272773276",
        email: "gyateman12@acquirethisname.com",
        address: "58005 Hudson Way",
    },
    {
        name: "Gabie Cupitt",
        age: 61,
        gender: "Female",
        phone_number: "8542965123",
        email: "gcupitt13@comsenz.com",
        address: "00255 Lakeland Parkway",
    },
    {
        name: "Graig Bedinn",
        age: 48,
        gender: "Male",
        phone_number: "1138711905",
        email: "gbedinn14@typepad.com",
        address: "60 Acker Alley",
    },
    {
        name: "Lucky Tacker",
        age: 81,
        gender: "Female",
        phone_number: "8286241213",
        email: "ltacker15@nba.com",
        address: "8556 West Terrace",
    },
    {
        name: "Ronny Rudgerd",
        age: 33,
        gender: "Female",
        phone_number: "1678441528",
        email: "rrudgerd16@archive.org",
        address: "41 Jenifer Crossing",
    },
    {
        name: "Bellina Winch",
        age: 67,
        gender: "Female",
        phone_number: "6827912821",
        email: "bwinch17@zdnet.com",
        address: "8 Village Green Lane",
    },
    {
        name: "Dorella Rowesby",
        age: 78,
        gender: "Female",
        phone_number: "8714125615",
        email: "drowesby18@senate.gov",
        address: "77457 Rowland Junction",
    },
    {
        name: "Correy Raulstone",
        age: 57,
        gender: "Female",
        phone_number: "5208379654",
        email: "craulstone19@squidoo.com",
        address: "1 Moland Junction",
    },
    {
        name: "Danita McAdam",
        age: 67,
        gender: "Female",
        phone_number: "9363275340",
        email: "dmcadam1a@si.edu",
        address: "32 Moose Drive",
    },
    {
        name: "Lawton Lugden",
        age: 85,
        gender: "Male",
        phone_number: "8144199823",
        email: "llugden1b@4shared.com",
        address: "09 Summerview Lane",
    },
    {
        name: "Ely Triplett",
        age: 78,
        gender: "Male",
        phone_number: "2802847151",
        email: "etriplett1c@youtube.com",
        address: "18 Harper Park",
    },
    {
        name: "Lyndy Noods",
        age: 71,
        gender: "Female",
        phone_number: "2768259874",
        email: "lnoods1d@ted.com",
        address: "44436 Utah Drive",
    },
    {
        name: "Reiko Enderby",
        age: 74,
        gender: "Female",
        phone_number: "7363640038",
        email: "renderby1e@tripod.com",
        address: "843 Calypso Pass",
    },
    {
        name: "Ashlen Karolewski",
        age: 42,
        gender: "Female",
        phone_number: "1431496776",
        email: "akarolewski1f@aboutads.info",
        address: "930 Veith Place",
    },
    {
        name: "Byrann Skaif",
        age: 47,
        gender: "Male",
        phone_number: "1837866999",
        email: "bskaif1g@desdev.cn",
        address: "9 Bartillon Trail",
    },
    {
        name: "Kalie Dalliston",
        age: 55,
        gender: "Female",
        phone_number: "2302420324",
        email: "kdalliston1h@youtu.be",
        address: "34140 Sachs Point",
    },
    {
        name: "Nicoli Stutte",
        age: 64,
        gender: "Female",
        phone_number: "1588186279",
        email: "nstutte1i@usnews.com",
        address: "9812 Arrowood Plaza",
    },
    {
        name: "Kala Mordaunt",
        age: 33,
        gender: "Female",
        phone_number: "5282931538",
        email: "kmordaunt1j@apple.com",
        address: "1873 Washington Street",
    },
    {
        name: "Cami De Angelo",
        age: 75,
        gender: "Female",
        phone_number: "2939497082",
        email: "cde1k@soup.io",
        address: "9 Pond Place",
    },
    {
        name: "Dorris Hazeldene",
        age: 84,
        gender: "Female",
        phone_number: "2295206862",
        email: "dhazeldene1l@devhub.com",
        address: "08 Towne Crossing",
    },
    {
        name: "Reube Rubinfeld",
        age: 56,
        gender: "Male",
        phone_number: "3865435039",
        email: "rrubinfeld1m@arstechnica.com",
        address: "181 Michigan Park",
    },
    {
        name: "Konrad Randles",
        age: 70,
        gender: "Male",
        phone_number: "9246505707",
        email: "krandles1n@netvibes.com",
        address: "99 Express Junction",
    },
    {
        name: "Chicky Kloska",
        age: 31,
        gender: "Male",
        phone_number: "8896930755",
        email: "ckloska1o@msu.edu",
        address: "5479 Hooker Drive",
    },
    {
        name: "Merci Secrett",
        age: 82,
        gender: "Female",
        phone_number: "6008704503",
        email: "msecrett1p@hc360.com",
        address: "76 Dahle Place",
    },
    {
        name: "Neron Hogsden",
        age: 78,
        gender: "Male",
        phone_number: "2728419295",
        email: "nhogsden1q@devhub.com",
        address: "17608 Northwestern Trail",
    },
    {
        name: "Ruddy Ridgway",
        age: 82,
        gender: "Male",
        phone_number: "7388350292",
        email: "rridgway1r@scribd.com",
        address: "94669 4th Junction",
    },
    {
        name: "Alden Snawdon",
        age: 46,
        gender: "Male",
        phone_number: "6833836531",
        email: "asnawdon1s@myspace.com",
        address: "55 Summerview Road",
    },
    {
        name: "Cameron Brager",
        age: 30,
        gender: "Male",
        phone_number: "7907095409",
        email: "cbrager1t@freewebs.com",
        address: "4 North Hill",
    },
    {
        name: "Livia Pidon",
        age: 55,
        gender: "Female",
        phone_number: "6902222373",
        email: "lpidon1u@youtube.com",
        address: "4 Hayes Drive",
    },
    {
        name: "Adeline Stuffins",
        age: 35,
        gender: "Female",
        phone_number: "8125984732",
        email: "astuffins1v@goo.gl",
        address: "5 Oak Alley",
    },
    {
        name: "Nadean Cranmor",
        age: 65,
        gender: "Female",
        phone_number: "3432693355",
        email: "ncranmor1w@google.co.uk",
        address: "4 Oakridge Circle",
    },
    {
        name: "Terra Breach",
        age: 84,
        gender: "Female",
        phone_number: "1574019396",
        email: "tbreach1x@mit.edu",
        address: "78 Dottie Drive",
    },
    {
        name: "Joey Kalinovich",
        age: 85,
        gender: "Female",
        phone_number: "9625986265",
        email: "jkalinovich1y@wikipedia.org",
        address: "6 Porter Terrace",
    },
    {
        name: "Rozalie Cammis",
        age: 68,
        gender: "Female",
        phone_number: "5776691140",
        email: "rcammis1z@uiuc.edu",
        address: "19 High Crossing Lane",
    },
    {
        name: "Liva Sandbatch",
        age: 63,
        gender: "Female",
        phone_number: "7732635878",
        email: "lsandbatch20@artisteer.com",
        address: "870 Clove Street",
    },
    {
        name: "Turner Tromans",
        age: 36,
        gender: "Male",
        phone_number: "1278307035",
        email: "ttromans21@nymag.com",
        address: "08983 Dexter Plaza",
    },
    {
        name: "Tammi Evill",
        age: 75,
        gender: "Female",
        phone_number: "3949722701",
        email: "tevill22@networksolutions.com",
        address: "1615 Kedzie Way",
    },
    {
        name: "Jeniece Jordin",
        age: 71,
        gender: "Female",
        phone_number: "4091499063",
        email: "jjordin23@reuters.com",
        address: "1 Debs Park",
    },
    {
        name: "Clemmy Lavallie",
        age: 57,
        gender: "Female",
        phone_number: "5506495775",
        email: "clavallie24@cbc.ca",
        address: "8 Michigan Center",
    },
    {
        name: "Jodi Marking",
        age: 30,
        gender: "Female",
        phone_number: "7857811354",
        email: "jmarking25@clickbank.net",
        address: "23 Blackbird Point",
    },
    {
        name: "Tremain Matussevich",
        age: 72,
        gender: "Male",
        phone_number: "8459995589",
        email: "tmatussevich26@ameblo.jp",
        address: "76149 Fulton Place",
    },
    {
        name: "Sammy Hulles",
        age: 63,
        gender: "Male",
        phone_number: "3019999094",
        email: "shulles27@privacy.gov.au",
        address: "11 Kim Place",
    },
    {
        name: "Brander Wood",
        age: 42,
        gender: "Male",
        phone_number: "3388944456",
        email: "bwood28@delicious.com",
        address: "30577 Lotheville Junction",
    },
    {
        name: "Laurent Wardhaw",
        age: 72,
        gender: "Male",
        phone_number: "9534106919",
        email: "lwardhaw29@google.de",
        address: "1 Kingsford Way",
    },
    {
        name: "Bonnee Charman",
        age: 49,
        gender: "Female",
        phone_number: "8044692777",
        email: "bcharman2a@meetup.com",
        address: "4460 Stone Corner Court",
    },
    {
        name: "Vinni Biddles",
        age: 72,
        gender: "Female",
        phone_number: "5353331627",
        email: "vbiddles2b@cnbc.com",
        address: "23 Vidon Avenue",
    },
    {
        name: "Edwin Laughrey",
        age: 59,
        gender: "Male",
        phone_number: "8885720071",
        email: "elaughrey2c@patch.com",
        address: "1 Annamark Alley",
    },
    {
        name: "Cornell Taylot",
        age: 42,
        gender: "Male",
        phone_number: "8796145497",
        email: "ctaylot2d@gnu.org",
        address: "30 Vera Way",
    },
    {
        name: "Gabriela Rennox",
        age: 59,
        gender: "Female",
        phone_number: "4114431853",
        email: "grennox2e@slate.com",
        address: "939 Reindahl Junction",
    },
    {
        name: "Heidi Redd",
        age: 76,
        gender: "Female",
        phone_number: "4901638842",
        email: "hredd2f@cmu.edu",
        address: "64 Barnett Road",
    },
    {
        name: "Elden Shovelbottom",
        age: 61,
        gender: "Male",
        phone_number: "4224361045",
        email: "eshovelbottom2g@taobao.com",
        address: "860 Crownhardt Lane",
    },
    {
        name: "Elmo Hawarden",
        age: 70,
        gender: "Male",
        phone_number: "7514895921",
        email: "ehawarden2h@bravesites.com",
        address: "0518 Magdeline Circle",
    },
    {
        name: "Brent Sukbhans",
        age: 49,
        gender: "Male",
        phone_number: "3606003929",
        email: "bsukbhans2i@go.com",
        address: "274 Graceland Pass",
    },
    {
        name: "Alicia Casado",
        age: 81,
        gender: "Female",
        phone_number: "5923277463",
        email: "acasado2j@sogou.com",
        address: "49619 New Castle Alley",
    },
    {
        name: "Bradley Bonnavant",
        age: 74,
        gender: "Male",
        phone_number: "3764281763",
        email: "bbonnavant2k@bloglovin.com",
        address: "4900 Dennis Place",
    },
    {
        name: "Hamlin Gennerich",
        age: 50,
        gender: "Male",
        phone_number: "2034845749",
        email: "hgennerich2l@myspace.com",
        address: "0527 Di Loreto Hill",
    },
    {
        name: "Hercules Sprakes",
        age: 49,
        gender: "Male",
        phone_number: "7029887097",
        email: "hsprakes2m@google.co.uk",
        address: "72 Moulton Road",
    },
    {
        name: "Bradney Corragan",
        age: 55,
        gender: "Male",
        phone_number: "7539508037",
        email: "bcorragan2n@addtoany.com",
        address: "5 Armistice Crossing",
    },
    {
        name: "Charmion Van Castele",
        age: 46,
        gender: "Female",
        phone_number: "4393880980",
        email: "cvan2o@abc.net.au",
        address: "6824 Clyde Gallagher Circle",
    },
    {
        name: "Colet Cardoe",
        age: 31,
        gender: "Male",
        phone_number: "9829350202",
        email: "ccardoe2p@oaic.gov.au",
        address: "580 Fuller Trail",
    },
    {
        name: "Andriette Brice",
        age: 78,
        gender: "Female",
        phone_number: "6885142297",
        email: "abrice2q@microsoft.com",
        address: "127 Fisk Street",
    },
    {
        name: "Brooks Bassey",
        age: 40,
        gender: "Male",
        phone_number: "8068622310",
        email: "brooksbassey@yahoo.com",
        address: "5 Goodland Plaza",
    },
];


$(document).ready(function() {
    let tableData;
    for (let i = 0; i < data.length; i++) {
        tableData = `
      <tr class="table-row">
        <td class="tbody-td">${data[i].name}</td>
        <td class="tbody-td">${data[i].age}</td>
        <td class="tbody-td">${data[i].gender}</td>
        <td class="tbody-td">${data[i].phone_number}</td>
        <td class="tbody-td">${data[i].email}</td>
        <td class="tbody-td">${data[i].address}</td>
    </tr>
      `;
        $(".tbody").append(tableData);
    }
});


// Search automatically as you are typing
// $(document).ready(function() {
//     $("#myInput").on("keyup", function() {
//         let value = $(this).val().toLowerCase();
//         $("#table tr").filter(function() {
//             $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
//         });
//     });
// });

// search manually on button click
let myInput = document.getElementById("myInput"),
    myInputError = document.getElementById("myInputError");


searchbtn.onclick = function(e) {
    e.preventDefault();
    searchValue();

    // Reset Form Inputs
    myInput.value = "";
};

// Declare a function to validate and Submit the form
function searchValue() {
    if (myInput.value == "" || myInput.value == null) {
        myInput.nextElementSibling.innerHTML = "Input Required";
    } else {
        myInput.nextElementSibling.innerHTML = "";

        let value = $(myInput).val().toLowerCase();
        $("#table tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            console.log();
        });
    }
};



let collect = [{
        name: "Roxy Roisen",
        age: 59,
        gender: "Female",
        phone_number: "+92(507) 411 - 7230",
        email: "rroisen8 @msu.edu",
        address: "8540 Shelley Road",
    },
    {
        name: "Leesa Humm",
        age: 64,
        gender: "Female",
        phone_number: "+63(888) 225 - 4876",
        email: "lhumm7 @narod.ru",
        address: "21st Center",
    },
    {
        name: "Huntley Yushkov",
        age: 26,
        gender: "Male",
        phone_number: "+7(741) 480 - 6427",
        email: "hyushkov0@xrea.com",
        address: "1 Oakridge Alley",
    },
    {
        name: "Tomkin Borham",
        age: 28,
        gender: "Male",
        phone_number: "+86(826) 832 - 0039",
        email: "tborham6@addthis.com",
        address: "07 Ilene Court",
    },
    {
        name: "Kaine Burns",
        age: 35,
        gender: "Male",
        phone_number: "+95(344) 411 - 3174",
        email: "kburns5 @w3.org",
        address: "2921 Eastlawn Drive",
    },
    {
        name: "Mayer Langtree",
        age: 69,
        gender: "Male",
        phone_number: "+86(889) 443 - 1452",
        email: "mlangtree4 @toplist.cz",
        address: "83922 Ohio Junction Yushkov",
    },
    {
        name: "Colin Bispham",
        age: 55,
        gender: "Male",
        phone_number: "+86(853) 935 - 9207",
        email: "cbispham3 @comcast.net",
        address: "971 Dunning Point",
    },
    {
        name: "Carlos Sturdey",
        age: 35,
        gender: "Male",
        phone_number: "+380(932) 968 - 0627",
        email: "csturdey2 @wix.com",
        address: "722 Forest Dale Point",
    },
    {
        name: "Gasparo Songist",
        age: 55,
        gender: "Male",
        phone_number: "+63(849) 847 - 5620",
        email: "gsongist1 @jalbum.net",
        address: "10 Holy Cross Drive",
    },
    {
        name: "Lexi Wevell",
        age: 64,
        gender: "Female",
        phone_number: "+86(952) 163 - 1345",
        email: "lwevell9 @ovh.net",
        address: "93530 Huxley Plaza",
    },
    {
        name: "Brooks Bassey",
        age: 70,
        gender: "Male",
        phone_number: "+86(952) 163 - 1345",
        email: "Brooksbassey@ovh.net",
        address: "12 Huxley Plaza",
    },
    {
        name: "Adan Bracken",
        age: 50,
        gender: "Female",
        phone_number: "2492710523",
        email: "abracken0@webmd.com",
        address: "9 Darwin Street",
    },
    {
        name: "Etan Serraillier",
        age: 61,
        gender: "Male",
        phone_number: "4254152823",
        email: "eserraillier1@arstechnica.com",
        address: "1680 Buell Hill",
    },
    {
        name: "Felicity Binding",
        age: 64,
        gender: "Female",
        phone_number: "4011912221",
        email: "fbinding2@livejournal.com",
        address: "63951 Linden Junction",
    },
    {
        name: "Sadella Jackett",
        age: 83,
        gender: "Female",
        phone_number: "2167924064",
        email: "sjackett3@hp.com",
        address: "0 Westend Way",
    },
    {
        name: "Lonny Panner",
        age: 65,
        gender: "Male",
        phone_number: "7349006747",
        email: "lpanner4@themeforest.net",
        address: "33 Dixon Avenue",
    },
    {
        name: "Nadine Rivett",
        age: 50,
        gender: "Female",
        phone_number: "2234288688",
        email: "nrivett5@flavors.me",
        address: "6 Meadow Valley Trail",
    },
    {
        name: "Dilly Langdon",
        age: 37,
        gender: "Male",
        phone_number: "5993732572",
        email: "dlangdon6@odnoklassniki.ru",
        address: "46 Daystar Center",
    },
    {
        name: "Mayer Greguol",
        age: 76,
        gender: "Male",
        phone_number: "9167226269",
        email: "mgreguol7@time.com",
        address: "64 Fieldstone Street",
    },
    {
        name: "Raynard Tangye",
        age: 63,
        gender: "Male",
        phone_number: "9462755829",
        email: "rtangye8@techcrunch.com",
        address: "49365 Hansons Lane",
    },
    {
        name: "Lebbie Kernell",
        age: 33,
        gender: "Female",
        phone_number: "1807755135",
        email: "lkernell9@yandex.ru",
        address: "6968 New Castle Center",
    },
    {
        name: "Reeta Hackforth",
        age: 34,
        gender: "Female",
        phone_number: "1445212837",
        email: "rhackfortha@topsy.com",
        address: "128 Rusk Park",
    },
    {
        name: "Quintin Combe",
        age: 72,
        gender: "Male",
        phone_number: "2369536738",
        email: "qcombeb@wisc.edu",
        address: "982 Barby Junction",
    },
    {
        name: "Jdavie Antrobus",
        age: 39,
        gender: "Male",
        phone_number: "7207752671",
        email: "jantrobusc@cpanel.net",
        address: "2 Marquette Road",
    },
    {
        name: "Chanda Kinder",
        age: 65,
        gender: "Female",
        phone_number: "8161246224",
        email: "ckinderd@japanpost.jp",
        address: "45467 Northwestern Plaza",
    },
    {
        name: "Doralyn Spradbrow",
        age: 73,
        gender: "Female",
        phone_number: "5208757858",
        email: "dspradbrowe@cornell.edu",
        address: "13239 Hazelcrest Point",
    },
    {
        name: "Glenda Gleder",
        age: 34,
        gender: "Female",
        phone_number: "6975351237",
        email: "gglederf@tiny.cc",
        address: "835 Ronald Regan Center",
    },
    {
        name: "Frederique Aldham",
        age: 78,
        gender: "Female",
        phone_number: "6199951061",
        email: "faldhamg@woothemes.com",
        address: "2418 Warrior Center",
    },
    {
        name: "Morty Tufts",
        age: 66,
        gender: "Male",
        phone_number: "3966112113",
        email: "mtuftsh@multiply.com",
        address: "16 Loomis Court",
    },
    {
        name: "Wallie Andrivel",
        age: 36,
        gender: "Female",
        phone_number: "5251165682",
        email: "wandriveli@squidoo.com",
        address: "97961 Starling Crossing",
    },
    {
        name: "Tabby McCosker",
        age: 44,
        gender: "Female",
        phone_number: "7947246763",
        email: "tmccoskerj@washington.edu",
        address: "07 Mayfield Point",
    },
    {
        name: "Vasilis Gwinnell",
        age: 43,
        gender: "Male",
        phone_number: "8796741983",
        email: "vgwinnellk@pagesperso-orange.fr",
        address: "0353 Summerview Lane",
    },
    {
        name: "Ford Ilieve",
        age: 37,
        gender: "Male",
        phone_number: "3891534145",
        email: "filievel@wikimedia.org",
        address: "0 Reindahl Plaza",
    },
    {
        name: "Hussein Blazej",
        age: 81,
        gender: "Male",
        phone_number: "2744746573",
        email: "hblazejm@bloomberg.com",
        address: "4 Sugar Avenue",
    },
    {
        name: "Borden Giannini",
        age: 43,
        gender: "Male",
        phone_number: "5183878576",
        email: "bgianninin@wikimedia.org",
        address: "67276 Russell Road",
    },
    {
        name: "Devlin Olekhov",
        age: 54,
        gender: "Male",
        phone_number: "1806077398",
        email: "dolekhovo@hexun.com",
        address: "86 Merry Drive",
    },
    {
        name: "Kimberly Dundin",
        age: 35,
        gender: "Female",
        phone_number: "3635996024",
        email: "kdundinp@technorati.com",
        address: "91 Village Green Circle",
    },
    {
        name: "Raff Willsmore",
        age: 41,
        gender: "Male",
        phone_number: "9561768703",
        email: "rwillsmoreq@cyberchimps.com",
        address: "093 Norway Maple Trail",
    },
    {
        name: "Bertram Hempshall",
        age: 59,
        gender: "Male",
        phone_number: "9512004951",
        email: "bhempshallr@amazonaws.com",
        address: "6117 Lien Circle",
    },
    {
        name: "Odo Arsmith",
        age: 32,
        gender: "Male",
        phone_number: "9761278369",
        email: "oarsmiths@jalbum.net",
        address: "9830 Crowley Drive",
    },
    {
        name: "Launce Stucksbury",
        age: 60,
        gender: "Male",
        phone_number: "6934159980",
        email: "lstucksburyt@imageshack.us",
        address: "35 Center Hill",
    },
    {
        name: "Shem Lysons",
        age: 40,
        gender: "Male",
        phone_number: "2281862721",
        email: "slysonsu@chicagotribune.com",
        address: "1 3rd Alley",
    },
    {
        name: "Cristin Coldman",
        age: 51,
        gender: "Female",
        phone_number: "4795355964",
        email: "ccoldmanv@spotify.com",
        address: "39864 Clarendon Plaza",
    },
    {
        name: "Aile Bateman",
        age: 41,
        gender: "Female",
        phone_number: "3058089180",
        email: "abatemanw@list-manage.com",
        address: "4011 Oxford Street",
    },
    {
        name: "Danit Tosspell",
        age: 43,
        gender: "Female",
        phone_number: "4133218044",
        email: "dtosspellx@youku.com",
        address: "36 Vahlen Point",
    },
    {
        name: "Allianora Brimman",
        age: 77,
        gender: "Female",
        phone_number: "4979501155",
        email: "abrimmany@123-reg.co.uk",
        address: "015 Dawn Parkway",
    },
    {
        name: "Aguie McAdam",
        age: 50,
        gender: "Male",
        phone_number: "5106253014",
        email: "amcadamz@miitbeian.gov.cn",
        address: "2285 Kennedy Way",
    },
    {
        name: "Rosamond O'Dyvoie",
        age: 82,
        gender: "Female",
        phone_number: "6257203952",
        email: "rodyvoie10@amazon.com",
        address: "4709 Oxford Crossing",
    },
    {
        name: "Luci Ellwood",
        age: 83,
        gender: "Female",
        phone_number: "4931467974",
        email: "lellwood11@clickbank.net",
        address: "74273 Morrow Point",
    },
    {
        name: "Goraud Yateman",
        age: 63,
        gender: "Male",
        phone_number: "7272773276",
        email: "gyateman12@acquirethisname.com",
        address: "58005 Hudson Way",
    },
    {
        name: "Gabie Cupitt",
        age: 61,
        gender: "Female",
        phone_number: "8542965123",
        email: "gcupitt13@comsenz.com",
        address: "00255 Lakeland Parkway",
    },
    {
        name: "Graig Bedinn",
        age: 48,
        gender: "Male",
        phone_number: "1138711905",
        email: "gbedinn14@typepad.com",
        address: "60 Acker Alley",
    },
    {
        name: "Lucky Tacker",
        age: 81,
        gender: "Female",
        phone_number: "8286241213",
        email: "ltacker15@nba.com",
        address: "8556 West Terrace",
    },
    {
        name: "Ronny Rudgerd",
        age: 33,
        gender: "Female",
        phone_number: "1678441528",
        email: "rrudgerd16@archive.org",
        address: "41 Jenifer Crossing",
    },
    {
        name: "Bellina Winch",
        age: 67,
        gender: "Female",
        phone_number: "6827912821",
        email: "bwinch17@zdnet.com",
        address: "8 Village Green Lane",
    },
    {
        name: "Dorella Rowesby",
        age: 78,
        gender: "Female",
        phone_number: "8714125615",
        email: "drowesby18@senate.gov",
        address: "77457 Rowland Junction",
    },
    {
        name: "Correy Raulstone",
        age: 57,
        gender: "Female",
        phone_number: "5208379654",
        email: "craulstone19@squidoo.com",
        address: "1 Moland Junction",
    },
    {
        name: "Danita McAdam",
        age: 67,
        gender: "Female",
        phone_number: "9363275340",
        email: "dmcadam1a@si.edu",
        address: "32 Moose Drive",
    },
    {
        name: "Lawton Lugden",
        age: 85,
        gender: "Male",
        phone_number: "8144199823",
        email: "llugden1b@4shared.com",
        address: "09 Summerview Lane",
    },
    {
        name: "Ely Triplett",
        age: 78,
        gender: "Male",
        phone_number: "2802847151",
        email: "etriplett1c@youtube.com",
        address: "18 Harper Park",
    },
    {
        name: "Lyndy Noods",
        age: 71,
        gender: "Female",
        phone_number: "2768259874",
        email: "lnoods1d@ted.com",
        address: "44436 Utah Drive",
    },
    {
        name: "Reiko Enderby",
        age: 74,
        gender: "Female",
        phone_number: "7363640038",
        email: "renderby1e@tripod.com",
        address: "843 Calypso Pass",
    },
    {
        name: "Ashlen Karolewski",
        age: 42,
        gender: "Female",
        phone_number: "1431496776",
        email: "akarolewski1f@aboutads.info",
        address: "930 Veith Place",
    },
    {
        name: "Byrann Skaif",
        age: 47,
        gender: "Male",
        phone_number: "1837866999",
        email: "bskaif1g@desdev.cn",
        address: "9 Bartillon Trail",
    },
    {
        name: "Kalie Dalliston",
        age: 55,
        gender: "Female",
        phone_number: "2302420324",
        email: "kdalliston1h@youtu.be",
        address: "34140 Sachs Point",
    },
    {
        name: "Nicoli Stutte",
        age: 64,
        gender: "Female",
        phone_number: "1588186279",
        email: "nstutte1i@usnews.com",
        address: "9812 Arrowood Plaza",
    },
    {
        name: "Kala Mordaunt",
        age: 33,
        gender: "Female",
        phone_number: "5282931538",
        email: "kmordaunt1j@apple.com",
        address: "1873 Washington Street",
    },
    {
        name: "Cami De Angelo",
        age: 75,
        gender: "Female",
        phone_number: "2939497082",
        email: "cde1k@soup.io",
        address: "9 Pond Place",
    },
    {
        name: "Dorris Hazeldene",
        age: 84,
        gender: "Female",
        phone_number: "2295206862",
        email: "dhazeldene1l@devhub.com",
        address: "08 Towne Crossing",
    },
    {
        name: "Reube Rubinfeld",
        age: 56,
        gender: "Male",
        phone_number: "3865435039",
        email: "rrubinfeld1m@arstechnica.com",
        address: "181 Michigan Park",
    },
    {
        name: "Konrad Randles",
        age: 70,
        gender: "Male",
        phone_number: "9246505707",
        email: "krandles1n@netvibes.com",
        address: "99 Express Junction",
    },
    {
        name: "Chicky Kloska",
        age: 31,
        gender: "Male",
        phone_number: "8896930755",
        email: "ckloska1o@msu.edu",
        address: "5479 Hooker Drive",
    },
    {
        name: "Merci Secrett",
        age: 82,
        gender: "Female",
        phone_number: "6008704503",
        email: "msecrett1p@hc360.com",
        address: "76 Dahle Place",
    },
    {
        name: "Neron Hogsden",
        age: 78,
        gender: "Male",
        phone_number: "2728419295",
        email: "nhogsden1q@devhub.com",
        address: "17608 Northwestern Trail",
    },
    {
        name: "Ruddy Ridgway",
        age: 82,
        gender: "Male",
        phone_number: "7388350292",
        email: "rridgway1r@scribd.com",
        address: "94669 4th Junction",
    },
    {
        name: "Alden Snawdon",
        age: 46,
        gender: "Male",
        phone_number: "6833836531",
        email: "asnawdon1s@myspace.com",
        address: "55 Summerview Road",
    },
    {
        name: "Cameron Brager",
        age: 30,
        gender: "Male",
        phone_number: "7907095409",
        email: "cbrager1t@freewebs.com",
        address: "4 North Hill",
    },
    {
        name: "Livia Pidon",
        age: 55,
        gender: "Female",
        phone_number: "6902222373",
        email: "lpidon1u@youtube.com",
        address: "4 Hayes Drive",
    },
    {
        name: "Adeline Stuffins",
        age: 35,
        gender: "Female",
        phone_number: "8125984732",
        email: "astuffins1v@goo.gl",
        address: "5 Oak Alley",
    },
    {
        name: "Nadean Cranmor",
        age: 65,
        gender: "Female",
        phone_number: "3432693355",
        email: "ncranmor1w@google.co.uk",
        address: "4 Oakridge Circle",
    },
    {
        name: "Terra Breach",
        age: 84,
        gender: "Female",
        phone_number: "1574019396",
        email: "tbreach1x@mit.edu",
        address: "78 Dottie Drive",
    },
    {
        name: "Joey Kalinovich",
        age: 85,
        gender: "Female",
        phone_number: "9625986265",
        email: "jkalinovich1y@wikipedia.org",
        address: "6 Porter Terrace",
    },
    {
        name: "Rozalie Cammis",
        age: 68,
        gender: "Female",
        phone_number: "5776691140",
        email: "rcammis1z@uiuc.edu",
        address: "19 High Crossing Lane",
    },
    {
        name: "Liva Sandbatch",
        age: 63,
        gender: "Female",
        phone_number: "7732635878",
        email: "lsandbatch20@artisteer.com",
        address: "870 Clove Street",
    },
    {
        name: "Turner Tromans",
        age: 36,
        gender: "Male",
        phone_number: "1278307035",
        email: "ttromans21@nymag.com",
        address: "08983 Dexter Plaza",
    },
    {
        name: "Tammi Evill",
        age: 75,
        gender: "Female",
        phone_number: "3949722701",
        email: "tevill22@networksolutions.com",
        address: "1615 Kedzie Way",
    },
    {
        name: "Jeniece Jordin",
        age: 71,
        gender: "Female",
        phone_number: "4091499063",
        email: "jjordin23@reuters.com",
        address: "1 Debs Park",
    },
    {
        name: "Clemmy Lavallie",
        age: 57,
        gender: "Female",
        phone_number: "5506495775",
        email: "clavallie24@cbc.ca",
        address: "8 Michigan Center",
    },
    {
        name: "Jodi Marking",
        age: 30,
        gender: "Female",
        phone_number: "7857811354",
        email: "jmarking25@clickbank.net",
        address: "23 Blackbird Point",
    },
    {
        name: "Tremain Matussevich",
        age: 72,
        gender: "Male",
        phone_number: "8459995589",
        email: "tmatussevich26@ameblo.jp",
        address: "76149 Fulton Place",
    },
    {
        name: "Sammy Hulles",
        age: 63,
        gender: "Male",
        phone_number: "3019999094",
        email: "shulles27@privacy.gov.au",
        address: "11 Kim Place",
    },
    {
        name: "Brander Wood",
        age: 42,
        gender: "Male",
        phone_number: "3388944456",
        email: "bwood28@delicious.com",
        address: "30577 Lotheville Junction",
    },
    {
        name: "Laurent Wardhaw",
        age: 72,
        gender: "Male",
        phone_number: "9534106919",
        email: "lwardhaw29@google.de",
        address: "1 Kingsford Way",
    },
    {
        name: "Bonnee Charman",
        age: 49,
        gender: "Female",
        phone_number: "8044692777",
        email: "bcharman2a@meetup.com",
        address: "4460 Stone Corner Court",
    },
    {
        name: "Vinni Biddles",
        age: 72,
        gender: "Female",
        phone_number: "5353331627",
        email: "vbiddles2b@cnbc.com",
        address: "23 Vidon Avenue",
    },
    {
        name: "Edwin Laughrey",
        age: 59,
        gender: "Male",
        phone_number: "8885720071",
        email: "elaughrey2c@patch.com",
        address: "1 Annamark Alley",
    },
    {
        name: "Cornell Taylot",
        age: 42,
        gender: "Male",
        phone_number: "8796145497",
        email: "ctaylot2d@gnu.org",
        address: "30 Vera Way",
    },
    {
        name: "Gabriela Rennox",
        age: 59,
        gender: "Female",
        phone_number: "4114431853",
        email: "grennox2e@slate.com",
        address: "939 Reindahl Junction",
    },
    {
        name: "Heidi Redd",
        age: 76,
        gender: "Female",
        phone_number: "4901638842",
        email: "hredd2f@cmu.edu",
        address: "64 Barnett Road",
    },
    {
        name: "Elden Shovelbottom",
        age: 61,
        gender: "Male",
        phone_number: "4224361045",
        email: "eshovelbottom2g@taobao.com",
        address: "860 Crownhardt Lane",
    },
    {
        name: "Elmo Hawarden",
        age: 70,
        gender: "Male",
        phone_number: "7514895921",
        email: "ehawarden2h@bravesites.com",
        address: "0518 Magdeline Circle",
    },
    {
        name: "Brent Sukbhans",
        age: 49,
        gender: "Male",
        phone_number: "3606003929",
        email: "bsukbhans2i@go.com",
        address: "274 Graceland Pass",
    },
    {
        name: "Alicia Casado",
        age: 81,
        gender: "Female",
        phone_number: "5923277463",
        email: "acasado2j@sogou.com",
        address: "49619 New Castle Alley",
    },
    {
        name: "Bradley Bonnavant",
        age: 74,
        gender: "Male",
        phone_number: "3764281763",
        email: "bbonnavant2k@bloglovin.com",
        address: "4900 Dennis Place",
    },
    {
        name: "Hamlin Gennerich",
        age: 50,
        gender: "Male",
        phone_number: "2034845749",
        email: "hgennerich2l@myspace.com",
        address: "0527 Di Loreto Hill",
    },
    {
        name: "Hercules Sprakes",
        age: 49,
        gender: "Male",
        phone_number: "7029887097",
        email: "hsprakes2m@google.co.uk",
        address: "72 Moulton Road",
    },
    {
        name: "Bradney Corragan",
        age: 55,
        gender: "Male",
        phone_number: "7539508037",
        email: "bcorragan2n@addtoany.com",
        address: "5 Armistice Crossing",
    },
    {
        name: "Charmion Van Castele",
        age: 46,
        gender: "Female",
        phone_number: "4393880980",
        email: "cvan2o@abc.net.au",
        address: "6824 Clyde Gallagher Circle",
    },
    {
        name: "Colet Cardoe",
        age: 31,
        gender: "Male",
        phone_number: "9829350202",
        email: "ccardoe2p@oaic.gov.au",
        address: "580 Fuller Trail",
    },
    {
        name: "Andriette Brice",
        age: 78,
        gender: "Female",
        phone_number: "6885142297",
        email: "abrice2q@microsoft.com",
        address: "127 Fisk Street",
    },
    {
        name: "Gertrud Farncomb",
        age: 55,
        gender: "Female",
        phone_number: "4859964142",
        email: "gfarncomb2r@google.ru",
        address: "721 Goodland Plaza",
    },
];


$(document).ready(function() {
    let rest;
    for (let i = 0; i < collect.length; i++) {
        rest = `  
        <div class="card" id="detail">
            <p><b>Name:  ${data[i].name}</b></p>
            <p><b>Age:  ${data[i].age}</b></p>
            <p><b>Gender:  ${data[i].gender}</b></p>
            <p><b>Phone Number:  ${data[i].phone_number}</b></p>
            <p><b>Email Address:  ${data[i].email}</b></p>
            <p><b>Address:  ${data[i].address}</b></p>
        </div>`;
        $("#detail").append(rest);
    }
});